name = "climbing-database"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "climbing-db"
database_id = "1a6915ee-255c-4a03-97a5-17bd549578ef"